# https://github.com/adityatelange/hugo-PaperMod/wiki/Installation#sample-configyml=
baseURL: "https://ryan.thommes.me"
languageCode: en-us
title: Ryan Thommes
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

params:
  env: production
  keywords: [Ryan, Thommes, Resume, Portfolio, Blog]
  author: Ryan Thommes
  defaultTheme: dark # auto, dark, light
  disableThemeToggle: false

  assets:
    disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  label: 
    text: " "

  profileMode:
    enabled: true
    title: "Ryan Thommes" # optional default will be site title
    subtitle: "BS in CS @ UIC"
    imageUrl: "/rjt.jpg" # optional
    imageWidth: 216
    imageHeight: 216

  socialIcons:
    - name: email
      url: mailto:ryan@thommes.me
    - name: github
      url: "https://github.com/ryanthommes"
    - name: linkedin
      url: "https://www.linkedin.com/in/ryanthommes/"
    - name: twitter
      url: "https://www.twitter.com/ryanthommes/"
    - name: instagram
      url: "https://www.instagram.com/ryanthommes/"

menu:
  main:
    - identifier: about
      name: about
      url: "/"
      weight: 10
    - identifier: resume
      name: resume
      url: "/resume"
      weight: 20
    - identifier: archives
      name: archives
      url: "/archives"
      weight: 30
    - identifier: search
      name: 
      url: "/search"
      weight: 40
